name: mlflow-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - mlflow
      - scikit-learn
      - pandas
      - numpy
      - jupyter
      - pandas-datareader
      - yfinance

